http://example.com

https://example.com

http://www.example.com

https://www.example.com

https://example.com
GET /path

https://example.com
GET /path
id=12
goat:cheese

https://example.com
HEADER Accept: application/json
GET /path
id=12

example.com
H Content-Type: application/json
POST /goats
name=cheeseman

example.com
HEADER Content-Type: application/json
POST /goats
@input.txt
